# install with conda env create -f environment.yml

name: pet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.2
  - matplotlib>=3.2,<4.0
  - numpy=1.26
  - dash
  - dash-bootstrap-components
  - plotly
  - pip
